// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(native_markdown_ffiFFI)
import native_markdown_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_native_markdown_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_native_markdown_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureNativeMarkdownFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct MarkdownBlock: Equatable, Hashable {
    public var kind: MarkdownBlockKind
    public var text: String
    public var inlines: [MarkdownInline]
    public var tableRows: [MarkdownTableRow]
    public var level: UInt8
    public var language: String
    public var name: String
    public var title: String
    public var info: String
    public var alertType: MarkdownAlertType
    public var quoteDepth: UInt32
    public var listDepth: UInt32
    public var ordinal: UInt32
    public var checked: Bool
    public var listTight: Bool
    public var listDelimiter: MarkdownListDelimiter
    public var sourceStartLine: UInt32
    public var sourceEndLine: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: MarkdownBlockKind, text: String, inlines: [MarkdownInline], tableRows: [MarkdownTableRow], level: UInt8, language: String, name: String, title: String, info: String, alertType: MarkdownAlertType, quoteDepth: UInt32, listDepth: UInt32, ordinal: UInt32, checked: Bool, listTight: Bool, listDelimiter: MarkdownListDelimiter, sourceStartLine: UInt32, sourceEndLine: UInt32) {
        self.kind = kind
        self.text = text
        self.inlines = inlines
        self.tableRows = tableRows
        self.level = level
        self.language = language
        self.name = name
        self.title = title
        self.info = info
        self.alertType = alertType
        self.quoteDepth = quoteDepth
        self.listDepth = listDepth
        self.ordinal = ordinal
        self.checked = checked
        self.listTight = listTight
        self.listDelimiter = listDelimiter
        self.sourceStartLine = sourceStartLine
        self.sourceEndLine = sourceEndLine
    }

    

    
}

#if compiler(>=6)
extension MarkdownBlock: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownBlock: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownBlock {
        return
            try MarkdownBlock(
                kind: FfiConverterTypeMarkdownBlockKind.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                inlines: FfiConverterSequenceTypeMarkdownInline.read(from: &buf), 
                tableRows: FfiConverterSequenceTypeMarkdownTableRow.read(from: &buf), 
                level: FfiConverterUInt8.read(from: &buf), 
                language: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                info: FfiConverterString.read(from: &buf), 
                alertType: FfiConverterTypeMarkdownAlertType.read(from: &buf), 
                quoteDepth: FfiConverterUInt32.read(from: &buf), 
                listDepth: FfiConverterUInt32.read(from: &buf), 
                ordinal: FfiConverterUInt32.read(from: &buf), 
                checked: FfiConverterBool.read(from: &buf), 
                listTight: FfiConverterBool.read(from: &buf), 
                listDelimiter: FfiConverterTypeMarkdownListDelimiter.read(from: &buf), 
                sourceStartLine: FfiConverterUInt32.read(from: &buf), 
                sourceEndLine: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: MarkdownBlock, into buf: inout [UInt8]) {
        FfiConverterTypeMarkdownBlockKind.write(value.kind, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterSequenceTypeMarkdownInline.write(value.inlines, into: &buf)
        FfiConverterSequenceTypeMarkdownTableRow.write(value.tableRows, into: &buf)
        FfiConverterUInt8.write(value.level, into: &buf)
        FfiConverterString.write(value.language, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.info, into: &buf)
        FfiConverterTypeMarkdownAlertType.write(value.alertType, into: &buf)
        FfiConverterUInt32.write(value.quoteDepth, into: &buf)
        FfiConverterUInt32.write(value.listDepth, into: &buf)
        FfiConverterUInt32.write(value.ordinal, into: &buf)
        FfiConverterBool.write(value.checked, into: &buf)
        FfiConverterBool.write(value.listTight, into: &buf)
        FfiConverterTypeMarkdownListDelimiter.write(value.listDelimiter, into: &buf)
        FfiConverterUInt32.write(value.sourceStartLine, into: &buf)
        FfiConverterUInt32.write(value.sourceEndLine, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownBlock_lift(_ buf: RustBuffer) throws -> MarkdownBlock {
    return try FfiConverterTypeMarkdownBlock.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownBlock_lower(_ value: MarkdownBlock) -> RustBuffer {
    return FfiConverterTypeMarkdownBlock.lower(value)
}


public struct MarkdownDocument: Equatable, Hashable {
    public var blocks: [MarkdownBlock]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blocks: [MarkdownBlock]) {
        self.blocks = blocks
    }

    

    
}

#if compiler(>=6)
extension MarkdownDocument: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownDocument: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownDocument {
        return
            try MarkdownDocument(
                blocks: FfiConverterSequenceTypeMarkdownBlock.read(from: &buf)
        )
    }

    public static func write(_ value: MarkdownDocument, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeMarkdownBlock.write(value.blocks, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownDocument_lift(_ buf: RustBuffer) throws -> MarkdownDocument {
    return try FfiConverterTypeMarkdownDocument.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownDocument_lower(_ value: MarkdownDocument) -> RustBuffer {
    return FfiConverterTypeMarkdownDocument.lower(value)
}


public struct MarkdownInline: Equatable, Hashable {
    public var kind: MarkdownInlineKind
    public var text: String
    public var url: String
    public var title: String
    public var strong: Bool
    public var emphasis: Bool
    public var code: Bool
    public var strikethrough: Bool
    public var highlight: Bool
    public var inserted: Bool
    public var superscript: Bool
    public var underline: Bool
    public var `subscript`: Bool
    public var spoiler: Bool
    public var escaped: Bool
    public var mathDisplay: Bool
    public var mathDollars: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: MarkdownInlineKind, text: String, url: String, title: String, strong: Bool, emphasis: Bool, code: Bool, strikethrough: Bool, highlight: Bool, inserted: Bool, superscript: Bool, underline: Bool, `subscript`: Bool, spoiler: Bool, escaped: Bool, mathDisplay: Bool, mathDollars: Bool) {
        self.kind = kind
        self.text = text
        self.url = url
        self.title = title
        self.strong = strong
        self.emphasis = emphasis
        self.code = code
        self.strikethrough = strikethrough
        self.highlight = highlight
        self.inserted = inserted
        self.superscript = superscript
        self.underline = underline
        self.`subscript` = `subscript`
        self.spoiler = spoiler
        self.escaped = escaped
        self.mathDisplay = mathDisplay
        self.mathDollars = mathDollars
    }

    

    
}

#if compiler(>=6)
extension MarkdownInline: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownInline: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownInline {
        return
            try MarkdownInline(
                kind: FfiConverterTypeMarkdownInlineKind.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                strong: FfiConverterBool.read(from: &buf), 
                emphasis: FfiConverterBool.read(from: &buf), 
                code: FfiConverterBool.read(from: &buf), 
                strikethrough: FfiConverterBool.read(from: &buf), 
                highlight: FfiConverterBool.read(from: &buf), 
                inserted: FfiConverterBool.read(from: &buf), 
                superscript: FfiConverterBool.read(from: &buf), 
                underline: FfiConverterBool.read(from: &buf), 
                subscript: FfiConverterBool.read(from: &buf), 
                spoiler: FfiConverterBool.read(from: &buf), 
                escaped: FfiConverterBool.read(from: &buf), 
                mathDisplay: FfiConverterBool.read(from: &buf), 
                mathDollars: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MarkdownInline, into buf: inout [UInt8]) {
        FfiConverterTypeMarkdownInlineKind.write(value.kind, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterBool.write(value.strong, into: &buf)
        FfiConverterBool.write(value.emphasis, into: &buf)
        FfiConverterBool.write(value.code, into: &buf)
        FfiConverterBool.write(value.strikethrough, into: &buf)
        FfiConverterBool.write(value.highlight, into: &buf)
        FfiConverterBool.write(value.inserted, into: &buf)
        FfiConverterBool.write(value.superscript, into: &buf)
        FfiConverterBool.write(value.underline, into: &buf)
        FfiConverterBool.write(value.`subscript`, into: &buf)
        FfiConverterBool.write(value.spoiler, into: &buf)
        FfiConverterBool.write(value.escaped, into: &buf)
        FfiConverterBool.write(value.mathDisplay, into: &buf)
        FfiConverterBool.write(value.mathDollars, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownInline_lift(_ buf: RustBuffer) throws -> MarkdownInline {
    return try FfiConverterTypeMarkdownInline.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownInline_lower(_ value: MarkdownInline) -> RustBuffer {
    return FfiConverterTypeMarkdownInline.lower(value)
}


public struct MarkdownParseOptions: Equatable, Hashable {
    public var githubFlavored: Bool
    public var frontMatter: Bool
    public var comrakExtensions: Bool
    public var inlineFootnotes: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(githubFlavored: Bool, frontMatter: Bool, comrakExtensions: Bool, inlineFootnotes: Bool) {
        self.githubFlavored = githubFlavored
        self.frontMatter = frontMatter
        self.comrakExtensions = comrakExtensions
        self.inlineFootnotes = inlineFootnotes
    }

    

    
}

#if compiler(>=6)
extension MarkdownParseOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownParseOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownParseOptions {
        return
            try MarkdownParseOptions(
                githubFlavored: FfiConverterBool.read(from: &buf), 
                frontMatter: FfiConverterBool.read(from: &buf), 
                comrakExtensions: FfiConverterBool.read(from: &buf), 
                inlineFootnotes: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MarkdownParseOptions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.githubFlavored, into: &buf)
        FfiConverterBool.write(value.frontMatter, into: &buf)
        FfiConverterBool.write(value.comrakExtensions, into: &buf)
        FfiConverterBool.write(value.inlineFootnotes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownParseOptions_lift(_ buf: RustBuffer) throws -> MarkdownParseOptions {
    return try FfiConverterTypeMarkdownParseOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownParseOptions_lower(_ value: MarkdownParseOptions) -> RustBuffer {
    return FfiConverterTypeMarkdownParseOptions.lower(value)
}


public struct MarkdownTableCell: Equatable, Hashable {
    public var text: String
    public var inlines: [MarkdownInline]
    public var alignment: MarkdownTableAlignment

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, inlines: [MarkdownInline], alignment: MarkdownTableAlignment) {
        self.text = text
        self.inlines = inlines
        self.alignment = alignment
    }

    

    
}

#if compiler(>=6)
extension MarkdownTableCell: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownTableCell: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownTableCell {
        return
            try MarkdownTableCell(
                text: FfiConverterString.read(from: &buf), 
                inlines: FfiConverterSequenceTypeMarkdownInline.read(from: &buf), 
                alignment: FfiConverterTypeMarkdownTableAlignment.read(from: &buf)
        )
    }

    public static func write(_ value: MarkdownTableCell, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterSequenceTypeMarkdownInline.write(value.inlines, into: &buf)
        FfiConverterTypeMarkdownTableAlignment.write(value.alignment, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownTableCell_lift(_ buf: RustBuffer) throws -> MarkdownTableCell {
    return try FfiConverterTypeMarkdownTableCell.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownTableCell_lower(_ value: MarkdownTableCell) -> RustBuffer {
    return FfiConverterTypeMarkdownTableCell.lower(value)
}


public struct MarkdownTableRow: Equatable, Hashable {
    public var isHeader: Bool
    public var cells: [MarkdownTableCell]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(isHeader: Bool, cells: [MarkdownTableCell]) {
        self.isHeader = isHeader
        self.cells = cells
    }

    

    
}

#if compiler(>=6)
extension MarkdownTableRow: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownTableRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownTableRow {
        return
            try MarkdownTableRow(
                isHeader: FfiConverterBool.read(from: &buf), 
                cells: FfiConverterSequenceTypeMarkdownTableCell.read(from: &buf)
        )
    }

    public static func write(_ value: MarkdownTableRow, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.isHeader, into: &buf)
        FfiConverterSequenceTypeMarkdownTableCell.write(value.cells, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownTableRow_lift(_ buf: RustBuffer) throws -> MarkdownTableRow {
    return try FfiConverterTypeMarkdownTableRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownTableRow_lower(_ value: MarkdownTableRow) -> RustBuffer {
    return FfiConverterTypeMarkdownTableRow.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MarkdownAlertType: Equatable, Hashable {
    
    case none
    case note
    case tip
    case important
    case warning
    case caution





}

#if compiler(>=6)
extension MarkdownAlertType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownAlertType: FfiConverterRustBuffer {
    typealias SwiftType = MarkdownAlertType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownAlertType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .note
        
        case 3: return .tip
        
        case 4: return .important
        
        case 5: return .warning
        
        case 6: return .caution
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MarkdownAlertType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case .note:
            writeInt(&buf, Int32(2))
        
        
        case .tip:
            writeInt(&buf, Int32(3))
        
        
        case .important:
            writeInt(&buf, Int32(4))
        
        
        case .warning:
            writeInt(&buf, Int32(5))
        
        
        case .caution:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownAlertType_lift(_ buf: RustBuffer) throws -> MarkdownAlertType {
    return try FfiConverterTypeMarkdownAlertType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownAlertType_lower(_ value: MarkdownAlertType) -> RustBuffer {
    return FfiConverterTypeMarkdownAlertType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MarkdownBlockKind: Equatable, Hashable {
    
    case frontMatter
    case heading
    case paragraph
    case quote
    case descriptionList
    case descriptionTerm
    case descriptionDetails
    case footnoteDefinition
    case listItem
    case orderedListItem
    case taskItem
    case codeBlock
    case htmlBlock
    case table
    case alert
    case subtext
    case blockDirective
    case divider





}

#if compiler(>=6)
extension MarkdownBlockKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownBlockKind: FfiConverterRustBuffer {
    typealias SwiftType = MarkdownBlockKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownBlockKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .frontMatter
        
        case 2: return .heading
        
        case 3: return .paragraph
        
        case 4: return .quote
        
        case 5: return .descriptionList
        
        case 6: return .descriptionTerm
        
        case 7: return .descriptionDetails
        
        case 8: return .footnoteDefinition
        
        case 9: return .listItem
        
        case 10: return .orderedListItem
        
        case 11: return .taskItem
        
        case 12: return .codeBlock
        
        case 13: return .htmlBlock
        
        case 14: return .table
        
        case 15: return .alert
        
        case 16: return .subtext
        
        case 17: return .blockDirective
        
        case 18: return .divider
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MarkdownBlockKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .frontMatter:
            writeInt(&buf, Int32(1))
        
        
        case .heading:
            writeInt(&buf, Int32(2))
        
        
        case .paragraph:
            writeInt(&buf, Int32(3))
        
        
        case .quote:
            writeInt(&buf, Int32(4))
        
        
        case .descriptionList:
            writeInt(&buf, Int32(5))
        
        
        case .descriptionTerm:
            writeInt(&buf, Int32(6))
        
        
        case .descriptionDetails:
            writeInt(&buf, Int32(7))
        
        
        case .footnoteDefinition:
            writeInt(&buf, Int32(8))
        
        
        case .listItem:
            writeInt(&buf, Int32(9))
        
        
        case .orderedListItem:
            writeInt(&buf, Int32(10))
        
        
        case .taskItem:
            writeInt(&buf, Int32(11))
        
        
        case .codeBlock:
            writeInt(&buf, Int32(12))
        
        
        case .htmlBlock:
            writeInt(&buf, Int32(13))
        
        
        case .table:
            writeInt(&buf, Int32(14))
        
        
        case .alert:
            writeInt(&buf, Int32(15))
        
        
        case .subtext:
            writeInt(&buf, Int32(16))
        
        
        case .blockDirective:
            writeInt(&buf, Int32(17))
        
        
        case .divider:
            writeInt(&buf, Int32(18))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownBlockKind_lift(_ buf: RustBuffer) throws -> MarkdownBlockKind {
    return try FfiConverterTypeMarkdownBlockKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownBlockKind_lower(_ value: MarkdownBlockKind) -> RustBuffer {
    return FfiConverterTypeMarkdownBlockKind.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MarkdownInlineKind: Equatable, Hashable {
    
    case text
    case softBreak
    case lineBreak
    case code
    case html
    case link
    case image
    case footnoteReference
    case wikiLink
    case math





}

#if compiler(>=6)
extension MarkdownInlineKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownInlineKind: FfiConverterRustBuffer {
    typealias SwiftType = MarkdownInlineKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownInlineKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text
        
        case 2: return .softBreak
        
        case 3: return .lineBreak
        
        case 4: return .code
        
        case 5: return .html
        
        case 6: return .link
        
        case 7: return .image
        
        case 8: return .footnoteReference
        
        case 9: return .wikiLink
        
        case 10: return .math
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MarkdownInlineKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .text:
            writeInt(&buf, Int32(1))
        
        
        case .softBreak:
            writeInt(&buf, Int32(2))
        
        
        case .lineBreak:
            writeInt(&buf, Int32(3))
        
        
        case .code:
            writeInt(&buf, Int32(4))
        
        
        case .html:
            writeInt(&buf, Int32(5))
        
        
        case .link:
            writeInt(&buf, Int32(6))
        
        
        case .image:
            writeInt(&buf, Int32(7))
        
        
        case .footnoteReference:
            writeInt(&buf, Int32(8))
        
        
        case .wikiLink:
            writeInt(&buf, Int32(9))
        
        
        case .math:
            writeInt(&buf, Int32(10))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownInlineKind_lift(_ buf: RustBuffer) throws -> MarkdownInlineKind {
    return try FfiConverterTypeMarkdownInlineKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownInlineKind_lower(_ value: MarkdownInlineKind) -> RustBuffer {
    return FfiConverterTypeMarkdownInlineKind.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MarkdownListDelimiter: Equatable, Hashable {
    
    case none
    case period
    case paren





}

#if compiler(>=6)
extension MarkdownListDelimiter: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownListDelimiter: FfiConverterRustBuffer {
    typealias SwiftType = MarkdownListDelimiter

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownListDelimiter {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .period
        
        case 3: return .paren
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MarkdownListDelimiter, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case .period:
            writeInt(&buf, Int32(2))
        
        
        case .paren:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownListDelimiter_lift(_ buf: RustBuffer) throws -> MarkdownListDelimiter {
    return try FfiConverterTypeMarkdownListDelimiter.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownListDelimiter_lower(_ value: MarkdownListDelimiter) -> RustBuffer {
    return FfiConverterTypeMarkdownListDelimiter.lower(value)
}



public enum MarkdownParseError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InputTooLarge(bytes: UInt64, maxBytes: UInt64
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension MarkdownParseError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownParseError: FfiConverterRustBuffer {
    typealias SwiftType = MarkdownParseError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownParseError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InputTooLarge(
            bytes: try FfiConverterUInt64.read(from: &buf), 
            maxBytes: try FfiConverterUInt64.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MarkdownParseError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InputTooLarge(bytes,maxBytes):
            writeInt(&buf, Int32(1))
            FfiConverterUInt64.write(bytes, into: &buf)
            FfiConverterUInt64.write(maxBytes, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownParseError_lift(_ buf: RustBuffer) throws -> MarkdownParseError {
    return try FfiConverterTypeMarkdownParseError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownParseError_lower(_ value: MarkdownParseError) -> RustBuffer {
    return FfiConverterTypeMarkdownParseError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MarkdownTableAlignment: Equatable, Hashable {
    
    case none
    case left
    case center
    case right





}

#if compiler(>=6)
extension MarkdownTableAlignment: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownTableAlignment: FfiConverterRustBuffer {
    typealias SwiftType = MarkdownTableAlignment

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownTableAlignment {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .left
        
        case 3: return .center
        
        case 4: return .right
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MarkdownTableAlignment, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case .left:
            writeInt(&buf, Int32(2))
        
        
        case .center:
            writeInt(&buf, Int32(3))
        
        
        case .right:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownTableAlignment_lift(_ buf: RustBuffer) throws -> MarkdownTableAlignment {
    return try FfiConverterTypeMarkdownTableAlignment.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownTableAlignment_lower(_ value: MarkdownTableAlignment) -> RustBuffer {
    return FfiConverterTypeMarkdownTableAlignment.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMarkdownBlock: FfiConverterRustBuffer {
    typealias SwiftType = [MarkdownBlock]

    public static func write(_ value: [MarkdownBlock], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMarkdownBlock.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MarkdownBlock] {
        let len: Int32 = try readInt(&buf)
        var seq = [MarkdownBlock]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMarkdownBlock.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMarkdownInline: FfiConverterRustBuffer {
    typealias SwiftType = [MarkdownInline]

    public static func write(_ value: [MarkdownInline], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMarkdownInline.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MarkdownInline] {
        let len: Int32 = try readInt(&buf)
        var seq = [MarkdownInline]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMarkdownInline.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMarkdownTableCell: FfiConverterRustBuffer {
    typealias SwiftType = [MarkdownTableCell]

    public static func write(_ value: [MarkdownTableCell], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMarkdownTableCell.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MarkdownTableCell] {
        let len: Int32 = try readInt(&buf)
        var seq = [MarkdownTableCell]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMarkdownTableCell.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMarkdownTableRow: FfiConverterRustBuffer {
    typealias SwiftType = [MarkdownTableRow]

    public static func write(_ value: [MarkdownTableRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMarkdownTableRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MarkdownTableRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [MarkdownTableRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMarkdownTableRow.read(from: &buf))
        }
        return seq
    }
}
public func parseMarkdown(source: String, options: MarkdownParseOptions)throws  -> MarkdownDocument  {
    return try  FfiConverterTypeMarkdownDocument_lift(try rustCallWithError(FfiConverterTypeMarkdownParseError_lift) {
    uniffi_native_markdown_ffi_fn_func_parse_markdown(
        FfiConverterString.lower(source),
        FfiConverterTypeMarkdownParseOptions_lower(options),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_native_markdown_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_native_markdown_ffi_checksum_func_parse_markdown() != 8893) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureNativeMarkdownFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all